  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module merak::errors {

  #[error]

  const AssetNotFound: vector<u8> = b"Asset not found";

  public fun asset_not_found_error(condition: bool) {
    assert!(condition, AssetNotFound)
  }

  #[error]

  const AssetAlreadyDestroyed: vector<u8> = b"Asset already destroyed";

  public fun asset_already_destroyed_error(condition: bool) {
    assert!(condition, AssetAlreadyDestroyed)
  }

  #[error]

  const AssetNotLive: vector<u8> = b"Asset not live";

  public fun asset_not_live_error(condition: bool) {
    assert!(condition, AssetNotLive)
  }

  #[error]

  const AssetNotFrozen: vector<u8> = b"Asset not frozen";

  public fun asset_not_frozen_error(condition: bool) {
    assert!(condition, AssetNotFrozen)
  }

  #[error]

  const AccountNotFound: vector<u8> = b"Account not found";

  public fun account_not_found_error(condition: bool) {
    assert!(condition, AccountNotFound)
  }

  #[error]

  const AccountBlocked: vector<u8> = b"Account is blocked";

  public fun account_blocked_error(condition: bool) {
    assert!(condition, AccountBlocked)
  }

  #[error]

  const AccountFrozen: vector<u8> = b"Account is frozen";

  public fun account_frozen_error(condition: bool) {
    assert!(condition, AccountFrozen)
  }

  #[error]

  const BalanceTooLow: vector<u8> = b"Balance too low";

  public fun balance_too_low_error(condition: bool) {
    assert!(condition, BalanceTooLow)
  }

  #[error]

  const Overflows: vector<u8> = b"Operation overflows";

  public fun overflows_error(condition: bool) {
    assert!(condition, Overflows)
  }

  #[error]

  const NoPermission: vector<u8> = b"No permission";

  public fun no_permission_error(condition: bool) {
    assert!(condition, NoPermission)
  }

  #[error]

  const NotMintable: vector<u8> = b"Asset is not mintable";

  public fun not_mintable_error(condition: bool) {
    assert!(condition, NotMintable)
  }

  #[error]

  const NotBurnable: vector<u8> = b"Asset is not burnable";

  public fun not_burnable_error(condition: bool) {
    assert!(condition, NotBurnable)
  }

  #[error]

  const NotFreezable: vector<u8> = b"Asset is not freezable";

  public fun not_freezable_error(condition: bool) {
    assert!(condition, NotFreezable)
  }

  #[error]

  const PoolAlreadyExists: vector<u8> = b"Pool already exists";

  public fun pool_already_exists_error(condition: bool) {
    assert!(condition, PoolAlreadyExists)
  }

  #[error]

  const BelowMinAmount: vector<u8> = b"Amount is below minimum";

  public fun below_min_amount_error(condition: bool) {
    assert!(condition, BelowMinAmount)
  }

  #[error]

  const BelowMinLiquidity: vector<u8> = b"Amount is below Liquidity";

  public fun below_min_liquidity_error(condition: bool) {
    assert!(condition, BelowMinLiquidity)
  }

  #[error]

  const PoolNotFound: vector<u8> = b"Pool not found";

  public fun pool_not_found_error(condition: bool) {
    assert!(condition, PoolNotFound)
  }

  #[error]

  const MoreThanMaxSwapPathLen: vector<u8> = b"More than Max";

  public fun more_than_max_swap_path_len_error(condition: bool) {
    assert!(condition, MoreThanMaxSwapPathLen)
  }

  #[error]

  const SwapPathTooSmall: vector<u8> = b"Swap path too small";

  public fun swap_path_too_small_error(condition: bool) {
    assert!(condition, SwapPathTooSmall)
  }

  #[error]

  const ReservesCannotBeZero: vector<u8> = b"Reserve cannot be 0";

  public fun reserves_cannot_be_zero_error(condition: bool) {
    assert!(condition, ReservesCannotBeZero)
  }

  #[error]

  const AmountCannotBeZero: vector<u8> = b"Amount cannot be 0";

  public fun amount_cannot_be_zero_error(condition: bool) {
    assert!(condition, AmountCannotBeZero)
  }

  #[error]

  const LessThanAmountOutMin: vector<u8> = b"Less than expected";

  public fun less_than_amount_out_min_error(condition: bool) {
    assert!(condition, LessThanAmountOutMin)
  }

  #[error]

  const MoreThanAmountInMax: vector<u8> = b"More than expected";

  public fun more_than_amount_in_max_error(condition: bool) {
    assert!(condition, MoreThanAmountInMax)
  }
}
