  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: MIT
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module merak::wrapper_unwrapped_event {

  use sui::event;

  use std::ascii::String;

  public struct UnwrappedEvent has copy, drop {
    from: address,
    asset_id: u32,
    amount: u256,
    beneficiary: address,
  }

  public fun new(from: address, asset_id: u32, amount: u256, beneficiary: address): UnwrappedEvent {
    UnwrappedEvent {
                                   from,asset_id,amount,beneficiary
                               }
  }

  public fun emit(from: address, asset_id: u32, amount: u256, beneficiary: address) {
    event::emit(UnwrappedEvent {
                                   from,asset_id,amount,beneficiary
                               });
  }
}
