  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module merak::asset_details {

  use std::ascii::String;

  use merak::asset_status::AssetStatus;

  public struct AssetDetails has copy, drop, store {
    owner: address,
    supply: u256,
    accounts: u128,
    approvals: u128,
    status: AssetStatus,
    is_mintable: bool,
    is_burnable: bool,
    is_freezable: bool,
  }

  public fun new(
    owner: address,
    supply: u256,
    accounts: u128,
    approvals: u128,
    status: AssetStatus,
    is_mintable: bool,
    is_burnable: bool,
    is_freezable: bool,
  ): AssetDetails {
    AssetDetails {
                                   owner,supply,accounts,approvals,status,is_mintable,is_burnable,is_freezable
                               }
  }

  public fun get(self: &AssetDetails): (address,u256,u128,u128,AssetStatus,bool,bool,bool) {
    (self.owner,self.supply,self.accounts,self.approvals,self.status,self.is_mintable,self.is_burnable,self.is_freezable)
  }

  public fun get_owner(self: &AssetDetails): address {
    self.owner
  }

  public fun get_supply(self: &AssetDetails): u256 {
    self.supply
  }

  public fun get_accounts(self: &AssetDetails): u128 {
    self.accounts
  }

  public fun get_approvals(self: &AssetDetails): u128 {
    self.approvals
  }

  public fun get_status(self: &AssetDetails): AssetStatus {
    self.status
  }

  public fun get_is_mintable(self: &AssetDetails): bool {
    self.is_mintable
  }

  public fun get_is_burnable(self: &AssetDetails): bool {
    self.is_burnable
  }

  public fun get_is_freezable(self: &AssetDetails): bool {
    self.is_freezable
  }

  public(package) fun set_owner(self: &mut AssetDetails, owner: address) {
    self.owner = owner;
  }

  public(package) fun set_supply(self: &mut AssetDetails, supply: u256) {
    self.supply = supply;
  }

  public(package) fun set_accounts(self: &mut AssetDetails, accounts: u128) {
    self.accounts = accounts;
  }

  public(package) fun set_approvals(self: &mut AssetDetails, approvals: u128) {
    self.approvals = approvals;
  }

  public(package) fun set_status(self: &mut AssetDetails, status: AssetStatus) {
    self.status = status;
  }

  public(package) fun set_is_mintable(self: &mut AssetDetails, is_mintable: bool) {
    self.is_mintable = is_mintable;
  }

  public(package) fun set_is_burnable(self: &mut AssetDetails, is_burnable: bool) {
    self.is_burnable = is_burnable;
  }

  public(package) fun set_is_freezable(self: &mut AssetDetails, is_freezable: bool) {
    self.is_freezable = is_freezable;
  }

  public(package) fun set(
    self: &mut AssetDetails,
    owner: address,
    supply: u256,
    accounts: u128,
    approvals: u128,
    status: AssetStatus,
    is_mintable: bool,
    is_burnable: bool,
    is_freezable: bool,
  ) {
    self.owner = owner;
    self.supply = supply;
    self.accounts = accounts;
    self.approvals = approvals;
    self.status = status;
    self.is_mintable = is_mintable;
    self.is_burnable = is_burnable;
    self.is_freezable = is_freezable;
  }
}
