  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module merak::asset_wrapped_event {

  use sui::event;

  use std::ascii::String;

  use merak::account_status::AccountStatus;

  use merak::asset_status::AssetStatus;

  use merak::account::Account;

  use merak::asset_metadata::AssetMetadata;

  use merak::asset_details::AssetDetails;

  use merak::pool::Pool;

  use merak::path_element::PathElement;

  public struct AssetWrappedEvent has copy, drop {
    from: address,
    asset_id: u128,
    amount: u256,
    beneficiary: address,
  }

  public fun new(from: address, asset_id: u128, amount: u256, beneficiary: address): AssetWrappedEvent {
    AssetWrappedEvent {
                                   from,asset_id,amount,beneficiary
                               }
  }
}
