  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module merak::merak_asset_created_event {

  use sui::event;

  use std::ascii::String;

  use merak::merak_account_status::AccountStatus;

  use merak::merak_asset_status::AssetStatus;

  use merak::merak_asset_type::AssetType;

  use merak::merak_account::Account;

  use merak::merak_asset_metadata::AssetMetadata;

  use merak::merak_pool::Pool;

  use merak::merak_path_element::PathElement;

  use merak::merak_bridge_config::BridgeConfig;

  public struct AssetCreatedEvent has copy, drop {
    asset_id: u256,
    name: String,
    symbol: String,
    owner: address,
    is_mintable: bool,
    is_burnable: bool,
    is_freezable: bool,
  }

  public fun new(
    asset_id: u256,
    name: String,
    symbol: String,
    owner: address,
    is_mintable: bool,
    is_burnable: bool,
    is_freezable: bool,
  ): AssetCreatedEvent {
    AssetCreatedEvent {
                                   asset_id,name,symbol,owner,is_mintable,is_burnable,is_freezable
                               }
  }
}
