  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module merak::asset_transferred_event {

  use sui::event;

  use std::ascii::String;

  use merak::account_status::AccountStatus;

  use merak::asset_status::AssetStatus;

  use merak::account::Account;

  use merak::asset_metadata::AssetMetadata;

  use merak::asset_details::AssetDetails;

  use merak::pool::Pool;

  use merak::path_element::PathElement;

  public struct AssetTransferredEvent has copy, drop {
    asset_id: u128,
    from: address,
    to: address,
    amount: u256,
  }

  public fun new(asset_id: u128, from: address, to: address, amount: u256): AssetTransferredEvent {
    AssetTransferredEvent {
                                   asset_id,from,to,amount
                               }
  }
}
