  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module merak::merak_asset_unwrapped_event {

  use sui::event;

  use std::ascii::String;

  use merak::merak_account_status::AccountStatus;

  use merak::merak_asset_status::AssetStatus;

  use merak::merak_asset_type::AssetType;

  use merak::merak_account::Account;

  use merak::merak_asset_metadata::AssetMetadata;

  use merak::merak_pool::Pool;

  use merak::merak_path_element::PathElement;

  use merak::merak_bridge_config::BridgeConfig;

  public struct AssetUnwrappedEvent has copy, drop {
    from: address,
    asset_id: u256,
    amount: u256,
    beneficiary: address,
  }

  public fun new(from: address, asset_id: u256, amount: u256, beneficiary: address): AssetUnwrappedEvent {
    AssetUnwrappedEvent {
                                   from,asset_id,amount,beneficiary
                               }
  }
}
