  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module merak::merak_bridge_deposit_event {

  use sui::event;

  use std::ascii::String;

  use merak::merak_account_status::AccountStatus;

  use merak::merak_asset_status::AssetStatus;

  use merak::merak_account::Account;

  use merak::merak_asset_metadata::AssetMetadata;

  use merak::merak_pool::Pool;

  use merak::merak_path_element::PathElement;

  use merak::merak_bridge_config::BridgeConfig;

  public struct BridgeDepositEvent has copy, drop {
    asset_id: u256,
    from: address,
    to: address,
    from_chain: String,
    amount: u256,
  }

  public fun new(asset_id: u256, from: address, to: address, from_chain: String, amount: u256): BridgeDepositEvent {
    BridgeDepositEvent {
                                   asset_id,from,to,from_chain,amount
                               }
  }
}
