  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module merak::merak_bridge_config {

  use std::ascii::String;

  public struct BridgeConfig has copy, drop, store {
    fee: u256,
    opened: bool,
  }

  public fun new(fee: u256, opened: bool): BridgeConfig {
    BridgeConfig {
                                   fee,opened
                               }
  }

  public fun get(self: &BridgeConfig): (u256,bool) {
    (self.fee,self.opened)
  }

  public fun get_fee(self: &BridgeConfig): u256 {
    self.fee
  }

  public fun get_opened(self: &BridgeConfig): bool {
    self.opened
  }

  public(package) fun set_fee(self: &mut BridgeConfig, fee: u256) {
    self.fee = fee;
  }

  public(package) fun set_opened(self: &mut BridgeConfig, opened: bool) {
    self.opened = opened;
  }

  public(package) fun set(self: &mut BridgeConfig, fee: u256, opened: bool) {
    self.fee = fee;
    self.opened = opened;
  }
}
