  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module merak::merak_pool_created_event {

  use sui::event;

  use std::ascii::String;

  use merak::merak_account_status::AccountStatus;

  use merak::merak_asset_status::AssetStatus;

  use merak::merak_asset_type::AssetType;

  use merak::merak_account::Account;

  use merak::merak_asset_metadata::AssetMetadata;

  use merak::merak_pool::Pool;

  use merak::merak_path_element::PathElement;

  use merak::merak_bridge_config::BridgeConfig;

  public struct PoolCreatedEvent has copy, drop {
    creator: address,
    asset1_id: u256,
    asset2_id: u256,
    pool_address: address,
    lp_asset_id: u256,
    lp_asset_symbol: String,
  }

  public fun new(
    creator: address,
    asset1_id: u256,
    asset2_id: u256,
    pool_address: address,
    lp_asset_id: u256,
    lp_asset_symbol: String,
  ): PoolCreatedEvent {
    PoolCreatedEvent {
                                   creator,asset1_id,asset2_id,pool_address,lp_asset_id,lp_asset_symbol
                               }
  }
}
