  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module merak::merak_swap_executed_event {

  use sui::event;

  use std::ascii::String;

  use merak::merak_account_status::AccountStatus;

  use merak::merak_asset_status::AssetStatus;

  use merak::merak_account::Account;

  use merak::merak_asset_metadata::AssetMetadata;

  use merak::merak_pool::Pool;

  use merak::merak_path_element::PathElement;

  use merak::merak_bridge_config::BridgeConfig;

  public struct SwapExecutedEvent has copy, drop {
    who: address,
    send_to: address,
    amount_in: u256,
    amount_out: u256,
    path: vector<u256>,
  }

  public fun new(
    who: address,
    send_to: address,
    amount_in: u256,
    amount_out: u256,
    path: vector<u256>,
  ): SwapExecutedEvent {
    SwapExecutedEvent {
                                   who,send_to,amount_in,amount_out,path
                               }
  }
}
