  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: MIT
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  module poils::deploy_hook {

  use obelisk::dapps_schema::Dapps;

  use obelisk::dapps_system;

  use poils::dapp_key::DappKey;

  use std::ascii;
      use obelisk::wrapper_schema;
      use poils::assets_schema::Assets;

      use sui::clock::Clock;
      #[test_only]
      use obelisk::dapps_schema;
      #[test_only]
      use sui::clock;
      #[test_only]
      use sui::test_scenario;
      #[test_only]
      use sui::test_scenario::Scenario;

      public entry fun run(dapps: &mut Dapps, clock: &Clock, ctx: &mut TxContext) {
    // Register the dapp to obelisk.
    dapps_system::register<DappKey>(
            dapps,
            ascii::string(b"example"),
            ascii::string(b"example"),
            clock,
            ctx
        );
      poils::assets_schema::register(dapps, ctx);
      poils::dex_schema::register(dapps, ctx);
      poils::wrapper_schema::register(dapps, ctx);
    // Logic that needs to be automated once the contract is deployed


  }

  #[test_only]
  public fun deploy_hook_for_testing(): (Scenario, Dapps) {
      let mut scenario = test_scenario::begin(@0xA);
      {
          let ctx = test_scenario::ctx(&mut scenario);
          dapps_schema::init_dapps_for_testing(ctx);
          test_scenario::next_tx(&mut scenario,@0xA);
      };
      let mut dapps = test_scenario::take_shared<Dapps>(&scenario);
      let ctx = test_scenario::ctx(&mut scenario);
      let clock = clock::create_for_testing(ctx);
      run(&mut dapps, &clock, ctx);
      clock::destroy_for_testing(clock);
      test_scenario::next_tx(&mut scenario,@0xA);
      (scenario, dapps)
  }
}
