  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: MIT
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  module poils::assets_schema {

  use std::ascii::String;

  use std::type_name;

  use sui::transfer::{public_share_object};

  use obelisk::dapps_system;

  use obelisk::dapps_schema::Dapps;

  use obelisk::storage_value::{Self, StorageValue};

  use obelisk::storage_map::{Self, StorageMap};

  use obelisk::storage_double_map::{Self, StorageDoubleMap};

  use poils::dapp_key::DappKey;

  use poils::assets_account_status::AccountStatus;

  use poils::assets_status::Status;

  use poils::assets_account::Account;

  use poils::assets_metadata::Metadata;

  use poils::assets_details::Details;

  public struct Assets has key, store {
    id: UID,
    next_asset_id: StorageValue<u32>,
    metadata: StorageMap<u32, Metadata>,
    details: StorageMap<u32, Details>,
    account: StorageDoubleMap<u32, address, Account>,
  }

  public fun borrow_next_asset_id(self: &Assets): &StorageValue<u32> {
    &self.next_asset_id
  }

  public(package) fun borrow_mut_next_asset_id(self: &mut Assets): &mut StorageValue<u32> {
    &mut self.next_asset_id
  }

  public fun borrow_metadata(self: &Assets): &StorageMap<u32, Metadata> {
    &self.metadata
  }

  public(package) fun borrow_mut_metadata(self: &mut Assets): &mut StorageMap<u32, Metadata> {
    &mut self.metadata
  }

  public fun borrow_details(self: &Assets): &StorageMap<u32, Details> {
    &self.details
  }

  public(package) fun borrow_mut_details(self: &mut Assets): &mut StorageMap<u32, Details> {
    &mut self.details
  }

  public fun borrow_account(self: &Assets): &StorageDoubleMap<u32, address, Account> {
    &self.account
  }

  public(package) fun borrow_mut_account(self: &mut Assets): &mut StorageDoubleMap<u32, address, Account> {
    &mut self.account
  }

  public entry fun register(dapps: &mut Dapps, ctx: &mut TxContext) {
    let package_id = dapps_system::current_package_id<DappKey>();
    assert!(dapps.borrow_metadata().contains_key(package_id), 0);
    assert!(dapps.borrow_admin().get(package_id) == ctx.sender(), 0);
    let schema = type_name::get<Assets>().into_string();
    assert!(!dapps.borrow_schemas().get(package_id).contains(&schema), 0);
    public_share_object(Assets {
                          id: object::new(ctx),
                          next_asset_id: storage_value::new(), metadata: storage_map::new(), details: storage_map::new(), account: storage_double_map::new(),
                        });
    dapps_system::add_schema<Assets>(dapps, package_id, ctx);
  }
}
