  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: MIT
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  module poils::assets_account {

  use std::ascii::String;

  use poils::assets_account_status::AccountStatus;

  use poils::assets_status::Status;

  public struct Account has copy, drop, store {
    balance: u64,
    status: AccountStatus,
  }

  public fun new(balance: u64, status: AccountStatus): Account {
    Account {
                                   balance,status
                               }
  }

  public fun get(self: &Account): (u64,AccountStatus) {
    (self.balance,self.status)
  }

  public fun get_balance(self: &Account): u64 {
    self.balance
  }

  public fun get_status(self: &Account): AccountStatus {
    self.status
  }

  public(package) fun set_balance(self: &mut Account, balance: u64) {
    self.balance = balance;
  }

  public(package) fun set_status(self: &mut Account, status: AccountStatus) {
    self.status = status;
  }

  public(package) fun set(self: &mut Account, balance: u64, status: AccountStatus) {
    self.balance = balance;
    self.status = status;
  }
}
