  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: MIT
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  module poils::dex_schema {

  use std::ascii::String;

  use std::type_name;

  use sui::transfer::{public_share_object};

  use obelisk::dapps_system;

  use obelisk::dapps_schema::Dapps;

  use obelisk::storage_value::{Self, StorageValue};

  use obelisk::storage_map::{Self, StorageMap};

  use obelisk::storage_double_map::{Self, StorageDoubleMap};

  use poils::dapp_key::DappKey;

  use poils::dex_pool::Pool;

  public struct Dex has key, store {
    id: UID,
    next_pool_id: StorageValue<u32>,
    pool_id: StorageDoubleMap<u32, u32, u32>,
    pools: StorageMap<u32, Pool>,
  }

  public fun borrow_next_pool_id(self: &Dex): &StorageValue<u32> {
    &self.next_pool_id
  }

  public(package) fun borrow_mut_next_pool_id(self: &mut Dex): &mut StorageValue<u32> {
    &mut self.next_pool_id
  }

  public fun borrow_pool_id(self: &Dex): &StorageDoubleMap<u32, u32, u32> {
    &self.pool_id
  }

  public(package) fun borrow_mut_pool_id(self: &mut Dex): &mut StorageDoubleMap<u32, u32, u32> {
    &mut self.pool_id
  }

  public fun borrow_pools(self: &Dex): &StorageMap<u32, Pool> {
    &self.pools
  }

  public(package) fun borrow_mut_pools(self: &mut Dex): &mut StorageMap<u32, Pool> {
    &mut self.pools
  }

  public entry fun register(dapps: &mut Dapps, ctx: &mut TxContext) {
    let package_id = dapps_system::current_package_id<DappKey>();
    assert!(dapps.borrow_metadata().contains_key(package_id), 0);
    assert!(dapps.borrow_admin().get(package_id) == ctx.sender(), 0);
    let schema = type_name::get<Dex>().into_string();
    assert!(!dapps.borrow_schemas().get(package_id).contains(&schema), 0);
    public_share_object(Dex {
                          id: object::new(ctx),
                          next_pool_id: storage_value::new(), pool_id: storage_double_map::new(), pools: storage_map::new(),
                        });
    dapps_system::add_schema<Dex>(dapps, package_id, ctx);
  }
}
