  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: MIT
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module merak::assets_blocked_address_event {

  use sui::event;

  use std::ascii::String;

  public struct BlockedAddressEvent has copy, drop {
    asset_id: u32,
    owner: address,
  }

  public fun new(asset_id: u32, owner: address): BlockedAddressEvent {
    BlockedAddressEvent {
                                   asset_id,owner
                               }
  }

  public fun emit(asset_id: u32, owner: address) {
    event::emit(BlockedAddressEvent {
                                   asset_id,owner
                               });
  }
}
