  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: MIT
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module merak::assets_thawed_address_event {

  use sui::event;

  use std::ascii::String;

  public struct ThawedAddressEvent has copy, drop {
    asset_id: u32,
    owner: address,
  }

  public fun new(asset_id: u32, owner: address): ThawedAddressEvent {
    ThawedAddressEvent {
                                   asset_id,owner
                               }
  }

  public fun emit(asset_id: u32, owner: address) {
    event::emit(ThawedAddressEvent {
                                   asset_id,owner
                               });
  }
}
