  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: MIT
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module merak::assets_minted_event {

  use sui::event;

  use std::ascii::String;

  public struct MintedEvent has copy, drop {
    asset_id: u32,
    to: address,
    amount: u256,
  }

  public fun new(asset_id: u32, to: address, amount: u256): MintedEvent {
    MintedEvent {
                                   asset_id,to,amount
                               }
  }

  public fun emit(asset_id: u32, to: address, amount: u256) {
    event::emit(MintedEvent {
                                   asset_id,to,amount
                               });
  }
}
