  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: MIT
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module merak::dex_pool_created_event {

  use sui::event;

  use std::ascii::String;

  public struct PoolCreatedEvent has copy, drop {
    creator: address,
    pool_id: u32,
    pool_address: address,
    asset1_id: u32,
    asset2_id: u32,
    lp_asset_id: u32,
    lp_asset_symbol: String,
  }

  public fun new(
    creator: address,
    pool_id: u32,
    pool_address: address,
    asset1_id: u32,
    asset2_id: u32,
    lp_asset_id: u32,
    lp_asset_symbol: String,
  ): PoolCreatedEvent {
    PoolCreatedEvent {
                                   creator,pool_id,pool_address,asset1_id,asset2_id,lp_asset_id,lp_asset_symbol
                               }
  }

  public fun emit(
    creator: address,
    pool_id: u32,
    pool_address: address,
    asset1_id: u32,
    asset2_id: u32,
    lp_asset_id: u32,
    lp_asset_symbol: String,
  ) {
    event::emit(PoolCreatedEvent {
                                   creator,pool_id,pool_address,asset1_id,asset2_id,lp_asset_id,lp_asset_symbol
                               });
  }
}
