  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: MIT
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module merak::assets_schema {

  use std::ascii::String;

  use std::ascii::string;

  use sui::package::UpgradeCap;

  use std::type_name;

  use dubhe::dapps_system;

  use dubhe::storage_migrate;

  use dubhe::dapps_schema::Dapps;

  use dubhe::storage_value::{Self, StorageValue};

  use dubhe::storage_map::{Self, StorageMap};

  use dubhe::storage_double_map::{Self, StorageDoubleMap};

  use merak::dapp_key::DappKey;

  use sui::dynamic_field as df;

  use merak::assets_account_status::AccountStatus;

  use merak::assets_status::Status;

  use merak::assets_account::Account;

  use merak::assets_metadata::Metadata;

  use merak::assets_details::Details;

  public struct Assets has key, store {
    id: UID,
  }

  public fun borrow_next_asset_id(self: &Assets): &StorageValue<u32> {
    storage_migrate::borrow_field(&self.id, b"next_asset_id")
  }

  public(package) fun borrow_mut_next_asset_id(self: &mut Assets): &mut StorageValue<u32> {
    storage_migrate::borrow_mut_field(&mut self.id, b"next_asset_id")
  }

  public fun borrow_metadata(self: &Assets): &StorageMap<u32, Metadata> {
    storage_migrate::borrow_field(&self.id, b"metadata")
  }

  public(package) fun borrow_mut_metadata(self: &mut Assets): &mut StorageMap<u32, Metadata> {
    storage_migrate::borrow_mut_field(&mut self.id, b"metadata")
  }

  public fun borrow_details(self: &Assets): &StorageMap<u32, Details> {
    storage_migrate::borrow_field(&self.id, b"details")
  }

  public(package) fun borrow_mut_details(self: &mut Assets): &mut StorageMap<u32, Details> {
    storage_migrate::borrow_mut_field(&mut self.id, b"details")
  }

  public fun borrow_account(self: &Assets): &StorageDoubleMap<u32, address, Account> {
    storage_migrate::borrow_field(&self.id, b"account")
  }

  public(package) fun borrow_mut_account(self: &mut Assets): &mut StorageDoubleMap<u32, address, Account> {
    storage_migrate::borrow_mut_field(&mut self.id, b"account")
  }

  public fun create(ctx: &mut TxContext): Assets {
    let mut id = object::new(ctx);
    storage_migrate::add_field<StorageValue<u32>>(&mut id, b"next_asset_id", storage_value::new());
    storage_migrate::add_field<StorageMap<u32, Metadata>>(&mut id, b"metadata", storage_map::new());
    storage_migrate::add_field<StorageMap<u32, Details>>(&mut id, b"details", storage_map::new());
    storage_migrate::add_field<StorageDoubleMap<u32, address, Account>>(&mut id, b"account", storage_double_map::new());
    Assets { id }
  }

  public fun migrate(_assets: &mut Assets, _cap: &UpgradeCap) {}

  // ======================================== View Functions ========================================

  public fun get_next_asset_id(self: &Assets): Option<u32> {
    self.borrow_next_asset_id().try_get()
  }

  public fun get_metadata(self: &Assets, key: u32): Option<Metadata> {
    self.borrow_metadata().try_get(key)
  }

  public fun get_metadata_keys(self: &Assets): vector<u32> {
    self.borrow_metadata().keys()
  }

  public fun get_metadata_values(self: &Assets): vector<Metadata> {
    self.borrow_metadata().values()
  }

  public fun get_details(self: &Assets, key: u32): Option<Details> {
    self.borrow_details().try_get(key)
  }

  public fun get_details_keys(self: &Assets): vector<u32> {
    self.borrow_details().keys()
  }

  public fun get_details_values(self: &Assets): vector<Details> {
    self.borrow_details().values()
  }

  public fun get_account(self: &Assets, key1: u32, key2: address): Option<Account> {
    self.borrow_account().try_get(key1, key2)
  }

  public fun get_account_keys(self: &Assets): (vector<u32>, vector<address>) {
    self.borrow_account().keys()
  }

  public fun get_account_values(self: &Assets): vector<Account> {
    self.borrow_account().values()
  }

  // =========================================================================================================
}
