  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: MIT
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module merak::dex_schema {

  use std::ascii::String;

  use std::ascii::string;

  use sui::package::UpgradeCap;

  use std::type_name;

  use dubhe::dapps_system;

  use dubhe::storage_migrate;

  use dubhe::dapps_schema::Dapps;

  use dubhe::storage_value::{Self, StorageValue};

  use dubhe::storage_map::{Self, StorageMap};

  use dubhe::storage_double_map::{Self, StorageDoubleMap};

  use merak::dapp_key::DappKey;

  use sui::dynamic_field as df;

  use merak::dex_pool::Pool;

  use merak::dex_path_element::PathElement;

  public struct Dex has key, store {
    id: UID,
  }

  public fun borrow_next_pool_id(self: &Dex): &StorageValue<u32> {
    storage_migrate::borrow_field(&self.id, b"next_pool_id")
  }

  public(package) fun borrow_mut_next_pool_id(self: &mut Dex): &mut StorageValue<u32> {
    storage_migrate::borrow_mut_field(&mut self.id, b"next_pool_id")
  }

  public fun borrow_swap_fee(self: &Dex): &StorageValue<u256> {
    storage_migrate::borrow_field(&self.id, b"swap_fee")
  }

  public(package) fun borrow_mut_swap_fee(self: &mut Dex): &mut StorageValue<u256> {
    storage_migrate::borrow_mut_field(&mut self.id, b"swap_fee")
  }

  public fun borrow_lp_fee(self: &Dex): &StorageValue<u256> {
    storage_migrate::borrow_field(&self.id, b"lp_fee")
  }

  public(package) fun borrow_mut_lp_fee(self: &mut Dex): &mut StorageValue<u256> {
    storage_migrate::borrow_mut_field(&mut self.id, b"lp_fee")
  }

  public fun borrow_fee_to(self: &Dex): &StorageValue<address> {
    storage_migrate::borrow_field(&self.id, b"fee_to")
  }

  public(package) fun borrow_mut_fee_to(self: &mut Dex): &mut StorageValue<address> {
    storage_migrate::borrow_mut_field(&mut self.id, b"fee_to")
  }

  public fun borrow_max_swap_path_len(self: &Dex): &StorageValue<u8> {
    storage_migrate::borrow_field(&self.id, b"max_swap_path_len")
  }

  public(package) fun borrow_mut_max_swap_path_len(self: &mut Dex): &mut StorageValue<u8> {
    storage_migrate::borrow_mut_field(&mut self.id, b"max_swap_path_len")
  }

  public fun borrow_min_liquidity(self: &Dex): &StorageValue<u256> {
    storage_migrate::borrow_field(&self.id, b"min_liquidity")
  }

  public(package) fun borrow_mut_min_liquidity(self: &mut Dex): &mut StorageValue<u256> {
    storage_migrate::borrow_mut_field(&mut self.id, b"min_liquidity")
  }

  public fun borrow_pool_id(self: &Dex): &StorageDoubleMap<u32, u32, u32> {
    storage_migrate::borrow_field(&self.id, b"pool_id")
  }

  public(package) fun borrow_mut_pool_id(self: &mut Dex): &mut StorageDoubleMap<u32, u32, u32> {
    storage_migrate::borrow_mut_field(&mut self.id, b"pool_id")
  }

  public fun borrow_pools(self: &Dex): &StorageMap<u32, Pool> {
    storage_migrate::borrow_field(&self.id, b"pools")
  }

  public(package) fun borrow_mut_pools(self: &mut Dex): &mut StorageMap<u32, Pool> {
    storage_migrate::borrow_mut_field(&mut self.id, b"pools")
  }

  public fun create(ctx: &mut TxContext): Dex {
    let mut id = object::new(ctx);
    storage_migrate::add_field<StorageValue<u32>>(&mut id, b"next_pool_id", storage_value::new());
    storage_migrate::add_field<StorageValue<u256>>(&mut id, b"swap_fee", storage_value::new());
    storage_migrate::add_field<StorageValue<u256>>(&mut id, b"lp_fee", storage_value::new());
    storage_migrate::add_field<StorageValue<address>>(&mut id, b"fee_to", storage_value::new());
    storage_migrate::add_field<StorageValue<u8>>(&mut id, b"max_swap_path_len", storage_value::new());
    storage_migrate::add_field<StorageValue<u256>>(&mut id, b"min_liquidity", storage_value::new());
    storage_migrate::add_field<StorageDoubleMap<u32, u32, u32>>(&mut id, b"pool_id", storage_double_map::new());
    storage_migrate::add_field<StorageMap<u32, Pool>>(&mut id, b"pools", storage_map::new());
    Dex { id }
  }

  public fun migrate(_dex: &mut Dex, _cap: &UpgradeCap) {}

  // ======================================== View Functions ========================================

  public fun get_next_pool_id(self: &Dex): Option<u32> {
    self.borrow_next_pool_id().try_get()
  }

  public fun get_swap_fee(self: &Dex): Option<u256> {
    self.borrow_swap_fee().try_get()
  }

  public fun get_lp_fee(self: &Dex): Option<u256> {
    self.borrow_lp_fee().try_get()
  }

  public fun get_fee_to(self: &Dex): Option<address> {
    self.borrow_fee_to().try_get()
  }

  public fun get_max_swap_path_len(self: &Dex): Option<u8> {
    self.borrow_max_swap_path_len().try_get()
  }

  public fun get_min_liquidity(self: &Dex): Option<u256> {
    self.borrow_min_liquidity().try_get()
  }

  public fun get_pool_id(self: &Dex, key1: u32, key2: u32): Option<u32> {
    self.borrow_pool_id().try_get(key1, key2)
  }

  public fun get_pool_id_keys(self: &Dex): (vector<u32>, vector<u32>) {
    self.borrow_pool_id().keys()
  }

  public fun get_pool_id_values(self: &Dex): vector<u32> {
    self.borrow_pool_id().values()
  }

  public fun get_pools(self: &Dex, key: u32): Option<Pool> {
    self.borrow_pools().try_get(key)
  }

  public fun get_pools_keys(self: &Dex): vector<u32> {
    self.borrow_pools().keys()
  }

  public fun get_pools_values(self: &Dex): vector<Pool> {
    self.borrow_pools().values()
  }

  // =========================================================================================================
}
