  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module merak::merak_deploy_hook {

  use merak::merak_schema::Schema;
  use merak::custom_schema;
  use merak::merak_wrapper_system;
  use merak::merak_bridge_config;
  use merak::dubhe::DUBHE;
  use sui::sui::SUI;
  use std::ascii::string;

  public(package) fun run(schema: &mut Schema, ctx: &mut TxContext) {
    custom_schema::add_to_schema(schema, ctx);

    schema.next_asset_id().set(0);
    // 0.03% swap fee
    schema.swap_fee().set(3);
    // 0.01% lp fee
    schema.lp_fee().set(1);
    schema.fee_to().set(ctx.sender());
    schema.max_swap_path_len().set(6);
    schema.min_liquidity().set(100);

    // bridge
    // to Dubhe_OS_Network => 1 DUBHE
    schema.bridge().set(string(b"Dubhe OS"), merak_bridge_config::new(50000000, 2000000, true));
    // to Aptos_Network => 1 DUBHE
    schema.bridge().set(string(b"Aptos"), merak_bridge_config::new(50000000, 2000000, true));

    merak_wrapper_system::do_register<SUI>(
      schema,
      string(b"Wrapped SUI"),
      string(b"wSUI"),
      string(b"Wrapped SUI"),
    9,
    string(b"https://cryptologos.cc/logos/sui-sui-logo.png?v=040"),
    string(b"")
    );
    merak_wrapper_system::do_register<DUBHE>(
      schema,
    string(b"Wrapped DUBHE"),
      string(b"wDUBHE"),
      string(b"Wrapped DUBHE"),
      7,
      string(b"https://raw.githubusercontent.com/0xobelisk/dubhe/refs/heads/main/assets/logo.jpg"),
      string(b"")
    );
  }
}
