  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module merak::deploy_hook {

  use merak::schema::Schema;
  use merak::wrapper_schema;

  public(package) fun run(schema: &mut Schema, ctx: &mut TxContext) {
    wrapper_schema::add_to_schema(schema, ctx);

    schema.next_asset_id().set(0);
    // 0.03% swap fee
    schema.swap_fee().set(3);
    // 0.01% lp fee
    schema.lp_fee().set(1);
    schema.fee_to().set(ctx.sender());
    schema.max_swap_path_len().set(6);
    schema.min_liquidity().set(100);
  }
}
