  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module merak::merak_dapp_key {

  /// Authorization token for the app.

  public struct DappKey has drop {}

  public(package) fun new(): DappKey {
    DappKey {  }
  }
}
