  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: MIT
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  module poils::dapp_key {

  /// Authorization token for the app.

  public struct DappKey has drop {}

  public(package) fun new(): DappKey {
    DappKey {  }
  }
}
